buffs_modifier_data = {
  ["Swimming with Sharks"] = { ["meat"] = 20 },
  ["Simply Irresistible"] = { ["combat"] = 5 },
  ["Silent Running"] = { ["combat"] = -5 },
  ["Arse-a'fire"] = { ["initiative"] = 25 },
  ["Eyes Wide Propped"] = { ["item"] = 25, ["meat"] = 50 },
  ["Natural 1"] = { ["initiative"] = -100 },
  ["No Vertigo"] = { ["initiative"] = 20 },
  ["Aspect of the GravyPlum Fairy"] = { ["item"] = 10 },
  ["Carrion' On"] = { ["meat"] = 60 },
  ["Je Ne Sais Porquoise"] = { ["meat"] = 6, ["item"] = 5 },
  ["Braaains"] = { ["meat"] = 50, ["initiative"] = -50 },
  ["Badger Underfoot"] = { ["meat"] = 20 },
  ["Dance Interpreter"] = { ["item"] = 20 },
  ["Hoity Toity"] = { ["item"] = 30 },
  ["Fat Leon's Phat Loot Lyric"] = { ["item"] = 20 },
  ["The Vitus Virus"] = { ["item"] = 50 },
  ["Dilated Pupils"] = { ["item"] = 20 },
  ["Peppermint Twisted"] = { ["initiative"] = 40, ["meat"] = 50, ["ml"] = 10 },
  ["Extremely Poor Taste"] = { ["ml"] = 10 },
  ["Springy Fusilli"] = { ["initiative"] = 40 },
  ["Cupcake of Choice"] = { ["item"] = 30 },
  ["Grimace"] = { ["ml"] = 25 },
  ["Provocative Perkiness"] = { ["initiative"] = 20 },
  ["Material Witness"] = { ["meat"] = 10 },
  ["Melancholy Burden"] = { ["item"] = 60 },
  ["Gelded"] = { ["ml"] = 5 },
  ["The Ballad of Richie Thingfinder"] = { ["meat"] = 50, ["item"] = 20 },
  ["Perceptive Pressure"] = { ["item"] = 50 },
  ["Juiced and Jacked"] = { ["item"] = 20, ["ml"] = 10 },
  ["Cravin' for a Ravin'"] = { ["meat"] = 100 },
  ["Red Tongue"] = { ["meat"] = 50 },
  ["Socialismydia"] = { ["item"] = -50 },
  ["Fishily Speeding"] = { ["initiative"] = 50 },
  ["Blue Tongue"] = { ["item"] = 30 },
  ["Head on Fire, Ass Catching"] = { ["initiative"] = 10 },
  ["Wasabi Sinuses"] = { ["meat"] = 30, ["item"] = -10 },
  ["La Bamba"] = { ["item"] = 3 },
  ["Cranberry Cordiality"] = { ["meat"] = 10 },
  ["Extra Sensory Perception"] = { ["item"] = 50 },
  ["Black Face"] = { ["initiative"] = -40 },
  ["Big Veiny Brain"] = { ["meat"] = -20, ["item"] = -10 },
  ["Carlweather's Cantata of Confrontation"] = { ["combat"] = 5 },
  ["Well-Swabbed Ear"] = { ["initiative"] = 30 },
  ["On Pins and Needles"] = { ["initiative"] = 23 },
  ["Abominably Slippery"] = { ["initiative"] = 20 },
  ["Joyful Resolve"] = { ["item"] = 15 },
  ["Ticking Clock"] = { ["initiative"] = 30 },
  ["Temporary Blindness"] = { ["item"] = -75, ["initiative"] = -30 },
  ["Bootyliciousness"] = { ["item"] = 10 },
  ["Hella Smooth"] = { ["meat"] = 40, ["item"] = 20 },
  ["Hustlin'"] = { ["initiative"] = 50, ["item"] = 10 },
  ["Ass Over Teakettle"] = { ["initiative"] = 50 },
  ["Flashing Eyes"] = { ["meat"] = 30 },
  ["Hippy Stench"] = { ["combat"] = 5 },
  ["Disquiet Riot"] = { ["combat"] = -20 },
  ["All Fired Up"] = { ["initiative"] = 30 },
  ["Chihuahua Underfoot"] = { ["ml"] = 20 },
  ["Hombre Muerto Caminando"] = { ["initiative"] = 20 },
  ["Polka of Plenty"] = { ["meat"] = 50 },
  ["Fondid"] = { ["ml"] = 15 },
  ["Assaulted with Pepper"] = { ["ml"] = 20 },
  ["Cockroach Scurry"] = { ["initiative"] = 50 },
  ["Lapdog"] = { ["initiative"] = 30, ["ml"] = 20 },
  ["Blackberry Politeness"] = { ["meat"] = 20 },
  ["Hip to Be Square Dancin'"] = { ["item"] = 10 },
  ["Barking Dogs"] = { ["initiative"] = -50 },
  ["Heart of Lavender"] = { ["item"] = 10 },
  ["20/20 Vision"] = { ["item"] = 10 },
  ["Cletus's Canticle of Celerity"] = { ["initiative"] = 20 },
  ["Contemptible Emanations"] = { ["ml"] = 20 },
  ["Metal Speed"] = { ["initiative"] = 20 },
  ["Litterboxing"] = { ["item"] = 15 },
  ["Clyde's Blessing"] = { ["item"] = 50 },
  ["Spangled Star"] = { ["ml"] = 10 },
  ["Song of Fortune"] = { ["item"] = 25, ["meat"] = 50 },
  ["Your #1 Problem"] = { ["item"] = 100 },
  ["Ichorous Eyesight"] = { ["item"] = 10 },
  ["Okee-Dokee Go!"] = { ["initiative"] = 20 },
  ["Mmmmmelon"] = { ["item"] = 30 },
  ["Old School Pompadour"] = { ["initiative"] = 30 },
  ["Tranquilized Mind"] = { ["initiative"] = -1000 },
  ["Sinuses For Miles"] = { ["meat"] = 200 },
  ["Grulched"] = { ["ml"] = 20 },
  ["Dancing Prowess"] = { ["item"] = 15 },
  ["Zomg WTF"] = { ["ml"] = 30 },
  ["Make Meat FA$T!"] = { ["meat"] = 20 },
  ["Your Cupcake Senses Are Tingling"] = { ["meat"] = 30 },
  ["Loco Motives"] = { ["initiative"] = 10 },
  ["Winklered"] = { ["meat"] = 40 },
  ["White-boy Angst"] = { ["initiative"] = 50 },
  ["Weasels Underfoot"] = { ["item"] = 10 },
  ["Waking the Dead"] = { ["combat"] = 20 },
  ["Unpopular"] = { ["ml"] = 30 },
  ["Memory of Speed"] = { ["initiative"] = 200 },
  ["Ocelot Eyes"] = { ["item"] = 10 },
  ["Eau D'enmity"] = { ["ml"] = 5 },
  ["QWOPped Up"] = { ["initiative"] = -100 },
  ["The Sonata of Sneakiness"] = { ["combat"] = -5 },
  ["Greedy Resolve"] = { ["meat"] = 30 },
  ["The Cupcake of Wrath"] = { ["ml"] = 10 },
  ["Egg-stortionary Tactics"] = { ["meat"] = 50 },
  ["Techno Bliss"] = { ["item"] = 10 },
  ["Sweet and Yellow"] = { ["initiative"] = 10 },
  ["Super Vision"] = { ["item"] = 25 },
  ["Quadrilled"] = { ["item"] = 20 },
  ["Rave Concentration"] = { ["item"] = 30 },
  ["Sugar Rush"] = { ["initiative"] = 20 },
  ["Strawberry Alarm"] = { ["initiative"] = 50 },
  ["Sticky Fingers"] = { ["meat"] = 20 },
  ["Braaaaaains"] = { ["meat"] = 200, ["item"] = -50 },
  ["Song of Solitude"] = { ["combat"] = -20 },
  ["Song of Cockiness"] = { ["ml"] = 30 },
  ["Song of Battle"] = { ["combat"] = 20 },
  ["Livin' Large"] = { ["meat"] = 10 },
  ["So You Can Work More..."] = { ["meat"] = 10 },
  ["Smooth Movements"] = { ["combat"] = -5 },
  ["Can't Be a Chooser"] = { ["meat"] = 30 },
  ["Simply Invisible"] = { ["combat"] = -5 },
  ["Koyaaniskumquatsi"] = { ["ml"] = 30 },
  ["Slimebreath"] = { ["ml"] = 50 },
  ["El Tango de la Maldita Suegra"] = { ["initiative"] = 15 },
  ["Bilious"] = { ["ml"] = 25 },
  ["The Great Tit's Blessing"] = { ["ml"] = 20 },
  ["Discomfited"] = { ["initiative"] = 30 },
  ["Meatwise"] = { ["meat"] = 35 },
  ["Dances with Tweedles"] = { ["meat"] = 40 },
  ["Let's Go Shopping!"] = { ["item"] = 75, ["meat"] = 150 },
  ["One Very Clear Eye"] = { ["item"] = 100 },
  ["Fresh Scent"] = { ["combat"] = -5 },
  ["Heart of Yellow"] = { ["initiative"] = 20 },
  ["Holiday Bliss"] = { ["item"] = 20, ["meat"] = 20 },
  ["Eggs-tra Sensory Perception"] = { ["item"] = 10 },
  ["Ermine Eyes"] = { ["item"] = 5 },
  ["Rave Nirvana"] = { ["meat"] = 50 },
  ["Night Vision"] = { ["meat"] = 30 },
  ["Musk of the Moose"] = { ["combat"] = 5 },
  ["Object Detection"] = { ["item"] = 5 },
  ["Preternatural Greed"] = { ["meat"] = 100 },
  ["Eye of the Seal"] = { ["item"] = 10 },
  ["Black Tongue"] = { ["meat"] = 50, ["item"] = 30 },
  ["Peeled Eyeballs"] = { ["meat"] = -20, ["item"] = 15 },
  ["Natural 20"] = { ["initiative"] = 100 },
  ["Sizzling with Fury"] = { ["initiative"] = 60 },
  ["Memory of Aggressiveness"] = { ["ml"] = 30 },
  ["Heart of Pink"] = { ["meat"] = 20 },
  ["Oleaginous Soles"] = { ["initiative"] = 40 },
  ["Blessing of Pikachutlotal"] = { ["initiative"] = 30 },
  ["Hiding in Plain Sight"] = { ["initiative"] = 100 },
  ["Disco Nirvana"] = { ["meat"] = 30 },
  ["Digitally Converted"] = { ["ml"] = 30 },
  ["Scavengers Scavenging"] = { ["item"] = 20 },
  ["Simply Irritable"] = { ["ml"] = 15 },
  ["Aykrophobia"] = { ["item"] = 25, ["ml"] = 15 },
  ["Inky Camouflage"] = { ["combat"] = -5 },
  ["Disco Concentration"] = { ["item"] = 20 },
  ["5 Pounds Lighter"] = { ["initiative"] = 10 },
  ["Fearless"] = { ["ml"] = -10 },
  ["Broken Fast"] = { ["item"] = 30 },
  ["Low on the Hog"] = { ["meat"] = 100 },
  ["Extreme Muscle Relaxation"] = { ["initiative"] = -50 },
}
