outfits_modifier_data = {
  ["Tapered Threads"] = { ["items"] = { [1] = "duct tape dockers", [2] = "duct tape fedora", [3] = "duct tape sword" }, ["bonuses"] = { ["initiative"] = 30 } },
  ["Legendary Regalia of the Groovelord"] = { ["items"] = { [1] = "Disco 'Fro Pick", [2] = "Seeger's Unstoppable Banjo", [3] = "Volartta's bellbottoms", [4] = "Bling of the New Wave" }, ["bonuses"] = { ["initiative"] = 50 } },
  ["Pork Elf Prizes"] = { ["items"] = { [1] = "pig-iron helm", [2] = "pig-iron shinguards", [3] = "pig-iron bracers" }, ["bonuses"] = { ["item"] = 10 } },
  ["Mining Gear"] = { ["items"] = { [1] = "miner's helmet", [2] = "7-Foot Dwarven mattock", [3] = "miner's pants" }, ["bonuses"] = { ["meat"] = 5 } },
  ["Bow Tux"] = { ["items"] = { [1] = "bow staff", [2] = "bowlegged pants", [3] = "bowler" }, ["bonuses"] = { ["item"] = 5 } },
  ["Glad Bag Glad Rags"] = { ["items"] = { [1] = "giant discarded plastic fork", [2] = "giant discarded bottlecap", [3] = "giant discarded torn-up glove" }, ["bonuses"] = { ["initiative"] = 10 } },
  ["Encephalic Ensemble"] = { ["items"] = { [1] = "Cerebral Cloche", [2] = "Cerebral Culottes", [3] = "Cerebral Crossbow" }, ["bonuses"] = { ["item"] = 5 } },
  ["Crimbo Duds"] = { ["items"] = { [1] = "Crimbo hat", [2] = "Crimbo pants", [3] = "Crimbo sword" }, ["bonuses"] = { ["item"] = 5 } },
  ["Furry Suit"] = { ["items"] = { [1] = "furry pants", [2] = "wolf mask" }, ["bonuses"] = { ["ml"] = 5 } },
  ["8-Bit Finery"] = { ["items"] = { [1] = "pixel hat", [2] = "pixel pants", [3] = "pixel sword" }, ["bonuses"] = { ["initiative"] = 25 } },
  ["Antique Arms and Armor"] = { ["items"] = { [1] = "antique greaves", [2] = "antique helmet", [3] = "antique spear", [4] = "antique shield" }, ["bonuses"] = { ["initiative"] = -10 } },
  ["Bits o' Honey"] = { ["items"] = { [1] = "honeycap", [2] = "honey dipper", [3] = "honeybritches" }, ["bonuses"] = { ["item"] = 5 } },
  ["Bounty-Hunting Rig"] = { ["items"] = { [1] = "bounty-hunting helmet", [2] = "bounty-hunting rifle", [3] = "bounty-hunting pants" }, ["bonuses"] = { ["item"] = 15 } },
  ["BRICKOfig Outfit"] = { ["items"] = { [1] = "BRICKO hat", [2] = "BRICKO sword", [3] = "BRICKO pants" }, ["bonuses"] = { ["item"] = 10 } },
}
