--add_choice_text("Wooof! Wooooooof!", { -- choice adventure number: 1106
--	["Throw a stick"] = { text = "" },
--	["Pet him"] = { text = "" },
--	["Teach him some tricks"] = { text = "" },
--})

--add_choice_text("Playing Fetch*", { -- choice adventure number: 1107
--	["Throw it into the distant bushes"] = { text = "" },
--	["Throw it into the nearby grass"] = { text = "" },
--	["Throw it down the road"] = { text = "" },
--})
