load_file("base", "base/settings-page.lua")
load_file("base", "base/fight-page.lua")
load_file("base", "base/other.lua")

load_file("interface", "interface/familiar-grid.lua")
load_file("interface", "interface/pvp.lua")
load_file("interface", "interface/skill-checker.lua")
load_file("interface", "interface/fullness.lua")
load_file("interface", "interface/crafting.lua")
load_file("interface", "interface/storage.lua")
load_file("interface", "interface/ascension-checklist.lua")
load_file("interface", "interface/charpane.lua")
load_file("interface", "interface/pulverize-groups.lua")
load_file("interface", "interface/semirare.lua")

load_file("item", "items/scary-copying.lua")
load_file("item", "items/fly-away.lua")
load_file("item", "items/leaflet.lua")
load_file("item", "items/clover.lua")
load_file("item", "items/halo.lua")

load_file("familiar", "familiars/butt-away.lua")
load_file("familiar", "familiars/llama.lua")
load_file("familiar", "familiars/sandworm.lua")
load_file("familiar", "familiars/rogue-program.lua")
load_file("familiar", "familiars/pixie.lua")
load_file("familiar", "familiars/slimeling.lua")
load_file("familiar", "familiars/he-boulder.lua")
load_file("familiar", "familiars/badger.lua")
load_file("familiar", "familiars/xenomorph.lua")
load_file("familiar", "familiars/fairychauns.lua")
load_file("familiar", "familiars/hipster.lua")
load_file("familiar", "familiars/artistic-goth-kid.lua")
load_file("familiar", "familiars/organ-grinder.lua")
load_file("familiar", "familiars/obtuse-angel.lua")
load_file("familiar", "familiars/bloovian-groose.lua")
load_file("familiar", "familiars/nanorhino.lua")

load_file("skill", "skills/summons.lua")

load_file("zone", "zones/vip-lounge.lua")
load_file("zone", "zones/dod.lua")
load_file("zone", "zones/plains.lua")
load_file("zone", "zones/knob.lua")
load_file("zone", "zones/crypt.lua")
load_file("zone", "zones/woods.lua")
load_file("zone", "zones/island.lua")
load_file("zone", "zones/pirates.lua")
load_file("zone", "zones/louvre.lua")
load_file("zone", "zones/louvre-simple.lua")
load_file("zone", "zones/spookyraven.lua")
load_file("zone", "zones/lvl11.lua")
load_file("zone", "zones/lvl12.lua")
load_file("zone", "zones/lair.lua")
load_file("zone", "zones/nemesis.lua")
load_file("zone", "zones/mountains.lua")
load_file("zone", "zones/beanstalk.lua")
load_file("zone", "zones/beach.lua")
load_file("zone", "zones/rats.lua")
load_file("zone", "zones/wandering-monsters.lua")
load_file("zone", "zones/space.lua")
load_file("zone", "zones/campground.lua")
load_file("zone", "zones/town.lua")
load_file("zone", "zones/hobopolis.lua")
load_file("zone", "zones/haunted-house.lua")
load_file("zone", "zones/sea.lua")

load_file("interface", "interface/automation.lua")
load_file("interface", "interface/counters.lua")
load_file("interface", "interface/chatpane.lua")
load_file("interface", "interface/inventory-collapse.lua")
load_file("interface", "interface/custom-charpane.lua")
load_file("interface", "interface/preview-chat-commands.lua")

load_file("automation", "automation/setup.lua")
load_file("automation", "automation/daily-visits.lua")
