load_file("base", "base/settings-page.lua")
load_file("base", "base/fight-page.lua")
load_file("base", "base/other.lua")

load_file("interface", "interface/familiar-grid.lua")
load_file("interface", "interface/pvp.lua")
load_file("interface", "interface/skill-checker.lua")
load_file("interface", "interface/fullness.lua")
load_file("interface", "interface/crafting.lua")
load_file("interface", "interface/storage.lua")
load_file("interface", "interface/ascension-checklist.lua")
load_file("interface", "interface/charpane.lua")
load_file("interface", "interface/pulverize-groups.lua")
load_file("interface", "interface/semirare.lua")

load_file("item", "items/scary-copying.lua")
load_file("item", "items/fly-away.lua")
load_file("item", "items/leaflet.lua")
load_file("item", "items/clover.lua")
load_file("item", "items/halo.lua")
load_file("interface", "items/beararms.lua")

load_file("familiar", "familiars/butt-away.lua")
load_file("familiar", "familiars/llama.lua")
load_file("familiar", "familiars/pixie.lua")
load_file("familiar", "familiars/slimeling.lua")
load_file("familiar", "familiars/he-boulder.lua")
load_file("familiar", "familiars/fairychauns.lua")
load_file("familiar", "familiars/hipster.lua")
load_file("familiar", "familiars/artistic-goth-kid.lua")
load_file("familiar", "familiars/organ-grinder.lua")
load_file("familiar", "familiars/obtuse-angel.lua")
load_file("familiar", "familiars/bloovian-groose.lua")
load_file("familiar", "familiars/nanorhino.lua")
load_file("familiar", "familiars/hatrack.lua")
load_file("familiar", "familiars/drops.lua")

load_file("skill", "skills/summons.lua")

load_file("zone", "zones/vip-lounge.lua")
load_file("zone", "zones/dod.lua")
load_file("zone", "zones/plains.lua")
load_file("zone", "zones/knob.lua")
load_file("zone", "zones/crypt.lua")
load_file("zone", "zones/woods.lua")
load_file("zone", "zones/island.lua")
load_file("zone", "zones/pirates.lua")
load_file("zone", "zones/louvre.lua")
load_file("zone", "zones/louvre-simple.lua")
load_file("zone", "zones/spookyraven.lua")
load_file("zone", "zones/lvl11.lua")
load_file("zone", "zones/lvl12.lua")
load_file("zone", "zones/lair.lua")
load_file("zone", "zones/nemesis.lua")
load_file("zone", "zones/mountains.lua")
load_file("zone", "zones/beanstalk.lua")
load_file("zone", "zones/beach.lua")
load_file("zone", "zones/rats.lua")
load_file("zone", "zones/wandering-monsters.lua")
load_file("zone", "zones/space.lua")
load_file("zone", "zones/campground.lua")
load_file("zone", "zones/town.lua")
load_file("zone", "zones/hobopolis.lua")
load_file("zone", "zones/haunted-house.lua")
load_file("zone", "zones/sea.lua")

load_file("interface", "interface/automation.lua")
load_file("interface", "interface/counters.lua")
load_file("interface", "interface/chatpane.lua")
load_file("interface", "interface/inventory-collapse.lua")
load_file("interface", "interface/custom-charpane.lua")
load_file("interface", "interface/preview-chat-commands.lua")
load_file("interface", "interface/tracked-variables.lua")

load_file("automation", "automation/setup.lua")
load_file("automation", "automation/daily-visits.lua")

load_file("other", "other/mmg-blocker.lua")
load_file("other", "other/visit-people-warnings.lua")
-- load_file("other", "other/chrome-volcano.lua")
-- load_file("other", "other/nemesis-fight-music.lua")
-- load_file("other", "other/hookah-printer.lua")

-- load_file("other", "other/log-everything.lua")

load_file("chat", "other/chat-pvp-announcements.lua")

load_file("chat", "other/chat-commands.lua")

-- load_file("interface", "other/itemdrop-decorator.lua")

load_file("chat", "other/afh-clan-chat.lua")
-- load_file("other", "other/afh-clan-chat-base.lua")
load_file("chat", "other/chat-highlighting.lua")

load_file("automation", "automation/settings.lua")
load_file("automation", "automation/macros.lua")
load_file("automation", "automation/scripts.lua")
load_file("automation", "automation/tasks.lua")
load_file("automation", "automation/ascension.lua")

load_file("automation", "automation/casual-macro.lua")
load_file("automation", "automation/casual-scripts.lua")

load_file("automation", "automation/nemesis.lua")
load_file("automation", "automation/suburbandis.lua")
load_file("automation", "automation/spaaace.lua")
load_file("automation", "automation/felonia.lua")
load_file("automation", "automation/castle-farming.lua")
load_file("automation", "automation/dungeon-fist.lua")
load_file("automation", "automation/a-quest-lol.lua")

load_file("interface", "other/twillo/buffs.lua")
load_file("interface", "other/twillo/outfits.lua")
load_file("interface", "other/twillo/equipment.lua")
load_file("interface", "other/twillo/combat-display.lua")
load_file("interface", "other/twillo/item-display.lua")
load_file("interface", "other/twillo/ml-display.lua")
load_file("interface", "other/twillo/init-display.lua")
load_file("interface", "other/twillo/meat-display.lua")
load_file("interface", "other/twillo/bonus-display.lua")

load_file("interface", "other/bmaher/compact-topmenu.lua")

load_file("interface", "other/demon_llama/monster-data.lua")
load_file("interface", "other/demon_llama/phylum-treasures.lua")
load_file("interface", "other/demon_llama/combat-tracking.lua")
load_file("interface", "other/demon_llama/flyers.lua")
load_file("interface", "other/demon_llama/fight-stats.lua")
load_file("warning", "other/demon_llama/dictionary-warning.lua")
load_file("interface", "other/demon_llama/hiddencity-spheres.lua")

load_file("interface", "other/nion/basement.lua")

load_file("interface", "other/chickencha/lvl12.lua")
load_file("interface", "other/chickencha/chess.lua")

load_file("interface", "other/superbachelor/blank-out.lua")

load_file("chat", "other/add-log-notes.lua")

load_file("interface", "other/lua-console.lua")

for _, f in ipairs(list_custom_autoload_script_files()) do
	load_file("custom autoload", "custom-autoload/" .. f)
end
