load_file("base", "base/settings-page.lua")
load_file("base", "base/fight-page.lua")
load_file("base", "base/choice-page.lua")
load_file("base", "base/info.lua")
load_file("base", "base/other.lua")
load_file("base", "base/mafiaexpression-evaluator.lua")
load_file("base", "base/npc-stores.lua")
load_file("base", "mechanics/game-mechanics.lua")
load_file("interface", "interface/tracked-variables.lua")
load_file("interface", "interface/familiar-info.lua")

load_file("data", "data/mine-aggregate-prediction.lua")

load_file("interface", "interface/familiar-grid.lua")
load_file("interface", "interface/pvp.lua")
load_file("interface", "interface/skill-checker.lua")
load_file("interface", "interface/fullness.lua")
load_file("interface", "interface/crafting.lua")
load_file("interface", "interface/storage.lua")
load_file("interface", "interface/ascension-checklist.lua")
load_file("interface", "interface/pulverize-groups.lua")
load_file("interface", "interface/semirare.lua")
load_file("interface", "interface/shop-item-count.lua")
load_file("interface", "interface/cosmic-kitchen.lua")
load_file("interface", "interface/modifier-maximizer.lua")
load_file("interface", "interface/quest-optimizer.lua")
load_file("interface", "interface/compute-net-worth.lua")
load_file("interface", "interface/outfit-slots.lua")
load_file("interface", "interface/elemental-resistance.lua")
load_file("interface", "interface/inventory-diff.lua")
load_file("interface", "interface/view-ascension-logs.lua")
load_file("interface", "interface/lightsout.lua")
load_file("interface", "interface/wiki-link.lua")

load_file("item", "items/scary-copying.lua")
load_file("item", "items/fly-away.lua")
load_file("item", "items/leaflet.lua")
load_file("item", "items/clover.lua")
load_file("item", "items/halo.lua")
load_file("item", "items/sugar-sheet.lua")
load_file("item", "items/pantsgiving.lua")
load_file("interface", "items/beararms.lua")

load_file("item", "classes/pastathrall.lua")

load_file("skill", "skills/summons.lua")
load_file("skill", "skills/inigo.lua")
load_file("skill", "skills/pastamancer-spells.lua")
load_file("skill", "skills/sauceror-spells.lua")
load_file("skill", "skills/ed-spells.lua")

load_file("familiar", "familiars/butt-away.lua")
load_file("familiar", "familiars/llama.lua")
load_file("familiar", "familiars/pixie.lua")
load_file("familiar", "familiars/slimeling.lua")
load_file("familiar", "familiars/he-boulder.lua")
load_file("familiar", "familiars/hipster.lua")
load_file("familiar", "familiars/artistic-goth-kid.lua")
load_file("familiar", "familiars/organ-grinder.lua")
load_file("familiar", "familiars/obtuse-angel.lua")
load_file("familiar", "familiars/reanimated-reanimator.lua")
load_file("familiar", "familiars/bloovian-groose.lua")
load_file("familiar", "familiars/nanorhino.lua")
load_file("familiar", "familiars/hatrack.lua")
load_file("familiar", "familiars/happy-medium.lua")
load_file("familiar", "familiars/drops.lua")
load_file("familiar", "familiars/steam-powered-cheerleader.lua")
load_file("familiar", "familiars/familiar-bonuses.lua")
load_file("familiar", "familiars/angry-jung-man.lua")

load_file("zone", "zones/wandering-monsters.lua")
load_file("zone", "zones/vip-lounge.lua")
load_file("zone", "zones/dod.lua")
load_file("zone", "zones/plains.lua")
load_file("zone", "zones/knob.lua")
load_file("zone", "zones/crypt.lua")
load_file("zone", "zones/woods.lua")
load_file("zone", "zones/island.lua")
load_file("zone", "zones/pirates.lua")
load_file("zone", "zones/spookyraven.lua")
load_file("zone", "zones/lvl11.lua")
load_file("zone", "zones/lvl12.lua")
load_file("zone", "zones/lair.lua")
load_file("zone", "zones/nemesis.lua")
load_file("zone", "zones/mountains.lua")
load_file("zone", "zones/mine-prediction.lua")
load_file("zone", "zones/beanstalk.lua")
load_file("zone", "zones/beach.lua")
load_file("zone", "zones/rats.lua")
load_file("zone", "zones/space.lua")
load_file("zone", "zones/campground.lua")
load_file("zone", "zones/town.lua")
load_file("zone", "zones/hobopolis.lua")
load_file("zone", "zones/haunted-house.lua")
load_file("zone", "zones/sea.lua")
load_file("zone", "zones/mad-tea-party.lua")
load_file("zone", "zones/trick-or-treat.lua")
load_file("zone", "zones/hiddencity.lua")
load_file("zone", "zones/dinseylandfill.lua")

load_file("interface", "interface/counters.lua")
load_file("interface", "interface/chatpane.lua")
load_file("interface", "interface/inventory-collapse.lua")
load_file("interface", "interface/custom-charpane.lua")
load_file("interface", "restricted/chit/custom-charpane-chit.lua")
load_file("interface", "interface/preview-chat-commands.lua")
load_file("interface", "interface/improve-typography.lua")

load_file("spading", "spading/encounter-simulator.lua")
load_file("spading", "spading/meatdrops.lua")

load_file("automation", "automation/setup.lua")
load_file("automation", "automation/readventuring.lua")
load_file("automation", "automation/daily-visits.lua")
load_file("automation", "automation/tune-flavour-of-magic.lua")
load_file("automation", "automation/trick-or-treat.lua")
load_file("automation", "automation/delete-spookyraven-kmail.lua")

load_file("other", "other/mmg-blocker.lua")
load_file("other", "adventure-warnings/visit-people-warnings.lua")
load_file("other", "adventure-warnings/adventure-notices.lua")
load_file("other", "adventure-warnings/check-florist-friar.lua")
-- load_file("other", "other/chrome-volcano.lua")
-- load_file("other", "other/nemesis-fight-music.lua")
-- load_file("other", "other/hookah-printer.lua")

-- load_file("other", "other/log-everything.lua")

load_file("chat", "chat/chat-kolmafia-links.lua")
load_file("chat", "chat/chat-pvp-announcements.lua")
load_file("chat", "chat/remove-fake-chat.lua")

load_file("chat", "chat/chat-commands.lua")
load_file("chat", "chat/chat-utils.lua")

-- load_file("interface", "other/itemdrop-decorator.lua")

load_file("chat", "chat/relay-chatbot.lua")
-- load_file("other", "other/afh-clan-chat-base.lua")
load_file("chat", "chat/highlighting.lua")

load_file("automation", "automation/settings.lua")
load_file("automation", "automation/macros.lua")
load_file("automation", "automation/scripts.lua")
load_file("automation", "automation/tasks.lua")
load_file("automation", "automation/ascension.lua")

--load_file("automation", "automation/casual-macro.lua")
--load_file("automation", "automation/casual-scripts.lua")

load_file("automation", "automation/nemesis.lua")
load_file("automation", "automation/suburbandis.lua")
load_file("automation", "automation/spaaace.lua")
load_file("automation", "automation/felonia.lua")
load_file("automation", "automation/castle-farming.lua")
load_file("automation", "automation/dungeon-fist.lua")
load_file("automation", "automation/a-quest-lol.lua")
load_file("automation", "automation/seahorse.lua")
load_file("automation", "automation/sea-violence.lua")
load_file("automation", "automation/sea-hatred.lua")

load_file("automation", "automation/aftercore-automation.lua")

load_file("interface", "items/equipment-bonuses.lua")
load_file("interface", "interface/display-bonuses.lua")
load_file("interface", "buffs/buff-bonuses.lua")
load_file("interface", "buffs/intrinsic-bonuses.lua")
load_file("interface", "skills/passive-bonuses.lua")

load_file("interface", "interface/compact-topmenu.lua")

load_file("interface", "other/demon_llama/monster-data.lua")
load_file("interface", "other/demon_llama/phylum-treasures.lua")
load_file("interface", "other/demon_llama/combat-tracking.lua")
load_file("interface", "other/demon_llama/flyers.lua")
load_file("interface", "other/demon_llama/fight-stats.lua")
load_file("warning", "other/demon_llama/dictionary-warning.lua")

load_file("interface", "other/nion/basement.lua")

load_file("automation", "automation/turn-in-war-items.lua")
load_file("automation", "automation/chess-puzzle.lua")
load_file("automation", "automation/wolf-game.lua")
load_file("interface", "items/chibibuddy.lua")

load_file("interface", "items/blank-out.lua")

load_file("chat", "interface/add-log-notes.lua")

load_file("interface", "interface/lua-console.lua")

load_file("other", "paths/moonsigns.lua")
load_file("other", "paths/jarlsberg.lua")
load_file("other", "paths/sneaky-pete.lua")
load_file("other", "paths/heavy-rains.lua")
load_file("other", "paths/ed.lua")
load_file("other", "paths/standard.lua")

load_file("interface", "interface/charpane.lua")

for _, f in ipairs(list_custom_autoload_script_files()) do
	load_file("custom autoload", f)
end
