add_choice_text("Deep Inside Grimace, Bow Chick-a Bow Bow", {
	["Have a Drink"] = "To the old guy (distention pill, dog hair pill)",
		["Go Back to the Glowy Tavern"] = "Back to the entrance",
		["Try That One Door"] = "To the sleeping quarters (distention pill, dog hair pill)",
			["Follow Captain Smirk"] = "Get distention pill",
			["Follow the Green Girl"] = "Get synthethic dog hair pill",
			["Take the Glowing Door"] = "Back to the entrance",
		["Try the Other Door, Man"] = "To the warehouse (EMU harness)",
			["Cross to the Cross"] = "Get healing buff",
			["Be the Duke of the Hazard"] = "Get E.M.U. harness",
			["Down the Hatch"] = "Back to the entrance",
	["Check out the Coat Check"] = "To the coat check (EMU harness, EMU helmet)",
		["Exit, Stage Left"] = "To the warehouse (EMU harness)",
		["Stage Right, Even"] = "To the hallway (EMU helmet)",
			["Try the Port Door"] = "Get 2 biscuits of elven hardtack and 2 bottles of elven squeeze",
			["Try the Starboard Door"] = "Get E.M.U. helmet",
			["Try the Aft Door"] = "Back to the entrance",
		["Back to the Tavern"] = "Back to the entrance",
	["Go to Your Campsite, Apparently"] = "To the campsite (redundant options)",
		["Take the Silver Door"] = "To the sleeping quarters (distention pill, dog hair pill)",
		["Take the Purple Door"] = "To the hallway (EMU helmet)",
})

add_choice_text("Deep Inside Ronald, Baby", {
	["Try the Swimming Pool"] = "To the swimming pool (EMU thrusters, EMU joystick)",
		["Back to the Lobby"] = "Back to the entrance",
		["To the Left, to the Left"] = "To the headcrab (EMU thrusters, myst buff)",
			["Take the Red Door"] = "Get E.M.U. rocket thrusters",
			["Take the Blue Door"] = "Get +5 mysticality/turn buff",
		["Right as Rain"] = "To the hallway (EMU joystick)",
			["Crawl through the Ventilation Duct"] = "Get E.M.U. joystick",
			["Take the Shaft, Heh Heh"] = "Get medi-pack and magi-pack",
			["Take the Hatch"] = "Back to the entrance",
	["Check out the Armory"] = "To the armory (redundant options)",
		["My Left Door"] = "To the hallway (EMU joystick)",
		["The Right Stuff, er, Door"] = "To the sleeping bunk (muscle buff, moxie buff)",
			["Take the Buff Door"] = "Get +5 muscle/turn buff",
			["Take the Skanky Door"] = "Get +5 moxie/turn buff",
	["Explore the Mess Hall"] = "To the mess hall (get +5 muscle/turn, +5 mysticality/turn, or +5 moxie/turn buff)",
		["Lobby-tarian"] = "Back to the entrance",
		["The Left Wing"] = "To the sleeping bunk (muscle buff, moxie buff)",
		["The Right Wing"] = "To the headcrab (EMU thrusters, myst buff)",
})
